[package]
name = "dotsnapshot"
version = "1.2.0"
edition = "2021"
rust-version = "1.2.0"
description = "A CLI utility to create snapshots of dotfiles and configuration for seamless backup and restoration"
license = "MIT"
repository = "https://github.com/tomerlichtash/dotsnapshot"
keywords = ["dotfiles", "backup", "configuration", "snapshots", "cli"]
categories = ["command-line-utilities", "config"]

[dependencies]
tokio = { version = "1.2.0"] }
async-trait = "0.1"
serde = { version = "1.2.0"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "1.2.0"] }
clap_complete = "4.0"
clap_mangen = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "1.2.0"] }
time = { version = "1.2.0"] }
sha2 = "0.10"
chrono = { version = "1.2.0"] }
dirs = "5.0"
which = "6.0"

[dev-dependencies]
tempfile = "3.0"
