[package]
name = "dotsnapshot"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
description = "A CLI utility to create snapshots of dotfiles and configuration for seamless backup and restoration"
license = "MIT"
repository = "https://github.com/tomerlichtash/dotsnapshot"
keywords = ["dotfiles", "backup", "configuration", "snapshots", "cli"]
categories = ["command-line-utilities", "config"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["local-time"] }
time = { version = "0.3", features = ["formatting", "local-offset"] }
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
which = "6.0"

[dev-dependencies]
tempfile = "3.0"
