# dotsnapshot configuration file
# This file configures the behavior of the dotsnapshot tool

# Output directory for snapshots (default: ./snapshots)
output_dir = "./.snapshots"

# Specific plugins to include (if not specified, all plugins run)
# Available plugins: homebrew, vscode, cursor, npm, static
# include_plugins = ["homebrew", "vscode", "static"]

# Custom plugin target paths - allows plugins to write to custom directories in snapshots
[plugins]
# VSCode plugins can share the same directory
vscode_settings = { target_path = "vscode" }
vscode_keybindings = { target_path = "vscode" }
vscode_extensions = { target_path = "vscode" }

# Cursor plugins can share the same directory
cursor_settings = { target_path = "cursor" }
cursor_keybindings = { target_path = "cursor" }
cursor_extensions = { target_path = "cursor" }

# Homebrew plugin
homebrew_brewfile = { target_path = "homebrew" }

# NPM plugins
npm_global_packages = { target_path = "npm" }
npm_config = { target_path = "npm" }

# Static files plugin with custom path and additional configuration
# [plugins.static]
# target_path = "my-dotfiles"
# files = [
#   "~/.zshrc",
#   "~/.gitconfig",
#   "~/dotfiles",
# ]
# ignore = [
#   ".git",
#   "*.key",
#   "*_rsa",
#   "known_hosts*",
# ]

# Legacy static plugin configuration (still supported for backward compatibility)
[static]
# files = [
#   "~/.zshrc",
# ]
# Glob patterns to ignore when copying files/directories
# ignore = [
#   ".git",           # Ignore all .git directories
#   "target",         # Ignore Rust build directories
#   "node_modules",   # Ignore Node.js dependencies
#   "*.key",          # Ignore private key files
#   "*_rsa",          # Ignore RSA private keys
#   "known_hosts*",   # Ignore SSH known hosts files
#   ".DS_Store",      # Ignore macOS metadata files
# ]

# Logging configuration
[logging]
# Enable verbose logging by default
verbose = true

# Time format for log timestamps (uses time crate format syntax)
time_format = "[year]-[month]-[day] [hour]:[minute]:[second]"