output_dir = "./.snapshots"

[logging]
verbose = true
time_format = "[year]-[month]-[day] [hour]:[minute]:[second]"

[hooks]
scripts_dir = "/Users/tomerlichtash/dev/projects/file-snapshots/tests/test-scripts"

[[global.hooks.pre-snapshot]]
action = "script"
command = "pre-snapshot-setup.sh"
args = []
timeout = 30

[global.hooks.pre-snapshot.env_vars]

[[global.hooks.pre-snapshot]]
action = "log"
message = "Starting dotsnapshot backup process at {timestamp}"
level = "info"

[[global.hooks.post-snapshot]]
action = "script"
command = "post-snapshot-cleanup.sh"
args = []
timeout = 30

[global.hooks.post-snapshot.env_vars]

[[global.hooks.post-snapshot]]
action = "notify"
message = "Backup completed successfully! 🎉"

[static]

[plugins.homebrew_brewfile]
target_path = "homebrew"

[plugins.homebrew_brewfile.hooks]
post-plugin = []

[[plugins.homebrew_brewfile.hooks.pre-plugin]]
action = "script"
command = "homebrew-pre-backup.sh"
args = []
timeout = 30

[plugins.homebrew_brewfile.hooks.pre-plugin.env_vars]

[plugins.vscode_settings]
target_path = "vscode"

[plugins.vscode_settings.hooks]
pre-plugin = []

[[plugins.vscode_settings.hooks.post-plugin]]
action = "script"
command = "vscode-post-backup.sh"
args = []
timeout = 30

[plugins.vscode_settings.hooks.post-plugin.env_vars]

[plugins.vscode_keybindings]
target_path = "vscode"

[plugins.vscode_extensions]
target_path = "vscode"

[plugins.cursor_settings]
target_path = "cursor"

[plugins.cursor_keybindings]
target_path = "cursor"

[plugins.cursor_extensions]
target_path = "cursor"

[plugins.npm_global_packages]
target_path = "npm"

[plugins.npm_config]
target_path = "npm"
