name: Semantic Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  semantic-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate commit messages
      uses: wagoid/commitlint-github-action@v6
      with:
        configFile: .commitlintrc.json
        failOnWarnings: true
        helpURL: 'https://www.conventionalcommits.org/'